// Code generated by gocc; DO NOT EDIT.

package lexer

import (
	"io/ioutil"
	"unicode/utf8"

	"github.com/awalterschulze/gominikanren/sexpr/token"
)

const (
	NoState    = -1
	NumStates  = 93
	NumSymbols = 59
)

type Lexer struct {
	src    []byte
	pos    int
	line   int
	column int
}

func NewLexer(src []byte) *Lexer {
	lexer := &Lexer{
		src:    src,
		pos:    0,
		line:   1,
		column: 1,
	}
	return lexer
}

func NewLexerFile(fpath string) (*Lexer, error) {
	src, err := ioutil.ReadFile(fpath)
	if err != nil {
		return nil, err
	}
	return NewLexer(src), nil
}

func (l *Lexer) Scan() (tok *token.Token) {
	tok = new(token.Token)
	if l.pos >= len(l.src) {
		tok.Type = token.EOF
		tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = l.pos, l.line, l.column
		return
	}
	start, startLine, startColumn, end := l.pos, l.line, l.column, 0
	tok.Type = token.INVALID
	state, rune1, size := 0, rune(-1), 0
	for state != -1 {
		if l.pos >= len(l.src) {
			rune1 = -1
		} else {
			rune1, size = utf8.DecodeRune(l.src[l.pos:])
			l.pos += size
		}

		nextState := -1
		if rune1 != -1 {
			nextState = TransTab[state](rune1)
		}
		state = nextState

		if state != -1 {

			switch rune1 {
			case '\n':
				l.line++
				l.column = 1
			case '\r':
				l.column = 1
			case '\t':
				l.column += 4
			default:
				l.column++
			}

			switch {
			case ActTab[state].Accept != -1:
				tok.Type = ActTab[state].Accept
				end = l.pos
			case ActTab[state].Ignore != "":
				start, startLine, startColumn = l.pos, l.line, l.column
				state = 0
				if start >= len(l.src) {
					tok.Type = token.EOF
				}

			}
		} else {
			if tok.Type == token.INVALID {
				end = l.pos
			}
		}
	}
	if end > start {
		l.pos = end
		tok.Lit = l.src[start:end]
	} else {
		tok.Lit = []byte{}
	}
	tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = start, startLine, startColumn

	return
}

func (l *Lexer) Reset() {
	l.pos = 0
}

/*
Lexer symbols:
0: ','
1: '-'
2: '-'
3: '('
4: ')'
5: '.'
6: '#'
7: '?'
8: '@'
9: '!'
10: '$'
11: '.'
12: '-'
13: '\'
14: ' '
15: '\'
16: 'x'
17: '\'
18: '\'
19: 'U'
20: '\'
21: 'u'
22: '\'
23: 'a'
24: 'b'
25: 'f'
26: 'n'
27: 'r'
28: 't'
29: 'v'
30: '\'
31: '''
32: '"'
33: '"'
34: '"'
35: '0'
36: '0'
37: 'x'
38: 'X'
39: 'e'
40: 'E'
41: '+'
42: '-'
43: '.'
44: '.'
45: '.'
46: ' '
47: '\t'
48: '\n'
49: '\r'
50: '0'-'9'
51: 'A'-'Z'
52: 'a'-'z'
53: '0'-'7'
54: '0'-'9'
55: 'A'-'F'
56: 'a'-'f'
57: '1'-'9'
58: .
*/
