// Code generated by gocc; DO NOT EDIT.

package lexer

/*
Let s be the current state
Let r be the current input rune
transitionTable[s](r) returns the next state.
*/
type TransitionTable [NumStates]func(rune) int

var TransTab = TransitionTable{
	// S0
	func(r rune) int {
		switch {
		case r == 9: // ['\t','\t']
			return 1
		case r == 10: // ['\n','\n']
			return 1
		case r == 13: // ['\r','\r']
			return 1
		case r == 32: // [' ',' ']
			return 1
		case r == 33: // ['!','!']
			return 2
		case r == 34: // ['"','"']
			return 3
		case r == 35: // ['#','#']
			return 2
		case r == 36: // ['$','$']
			return 2
		case r == 40: // ['(','(']
			return 4
		case r == 41: // [')',')']
			return 5
		case r == 44: // [',',',']
			return 6
		case r == 45: // ['-','-']
			return 7
		case r == 46: // ['.','.']
			return 8
		case r == 48: // ['0','0']
			return 9
		case 49 <= r && r <= 57: // ['1','9']
			return 10
		case r == 63: // ['?','?']
			return 2
		case r == 64: // ['@','@']
			return 2
		case 65 <= r && r <= 90: // ['A','Z']
			return 11
		case 97 <= r && r <= 122: // ['a','z']
			return 12
		}
		return NoState
	},
	// S1
	func(r rune) int {
		switch {
		case r == 9: // ['\t','\t']
			return 1
		case r == 10: // ['\n','\n']
			return 1
		case r == 13: // ['\r','\r']
			return 1
		case r == 32: // [' ',' ']
			return 1
		}
		return NoState
	},
	// S2
	func(r rune) int {
		switch {
		case r == 33: // ['!','!']
			return 13
		case r == 35: // ['#','#']
			return 13
		case r == 36: // ['$','$']
			return 13
		case r == 45: // ['-','-']
			return 14
		case r == 46: // ['.','.']
			return 13
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case r == 63: // ['?','?']
			return 13
		case r == 64: // ['@','@']
			return 13
		case 65 <= r && r <= 90: // ['A','Z']
			return 16
		case r == 92: // ['\','\']
			return 17
		case 97 <= r && r <= 122: // ['a','z']
			return 18
		}
		return NoState
	},
	// S3
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 19
		case r == 92: // ['\','\']
			return 20
		default:
			return 21
		}
	},
	// S4
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S5
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S6
	func(r rune) int {
		switch {
		case 97 <= r && r <= 122: // ['a','z']
			return 22
		}
		return NoState
	},
	// S7
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 23
		case r == 48: // ['0','0']
			return 24
		case 49 <= r && r <= 57: // ['1','9']
			return 25
		}
		return NoState
	},
	// S8
	func(r rune) int {
		switch {
		case r == 33: // ['!','!']
			return 13
		case r == 35: // ['#','#']
			return 13
		case r == 36: // ['$','$']
			return 13
		case r == 45: // ['-','-']
			return 14
		case r == 46: // ['.','.']
			return 13
		case 48 <= r && r <= 57: // ['0','9']
			return 26
		case r == 63: // ['?','?']
			return 13
		case r == 64: // ['@','@']
			return 13
		case 65 <= r && r <= 68: // ['A','D']
			return 16
		case r == 69: // ['E','E']
			return 27
		case 70 <= r && r <= 90: // ['F','Z']
			return 16
		case r == 92: // ['\','\']
			return 17
		case 97 <= r && r <= 100: // ['a','d']
			return 18
		case r == 101: // ['e','e']
			return 28
		case 102 <= r && r <= 122: // ['f','z']
			return 18
		}
		return NoState
	},
	// S9
	func(r rune) int {
		switch {
		case r == 33: // ['!','!']
			return 13
		case r == 35: // ['#','#']
			return 13
		case r == 36: // ['$','$']
			return 13
		case r == 45: // ['-','-']
			return 14
		case r == 46: // ['.','.']
			return 29
		case 48 <= r && r <= 55: // ['0','7']
			return 30
		case 56 <= r && r <= 57: // ['8','9']
			return 31
		case r == 63: // ['?','?']
			return 13
		case r == 64: // ['@','@']
			return 13
		case 65 <= r && r <= 68: // ['A','D']
			return 16
		case r == 69: // ['E','E']
			return 32
		case 70 <= r && r <= 87: // ['F','W']
			return 16
		case r == 88: // ['X','X']
			return 33
		case 89 <= r && r <= 90: // ['Y','Z']
			return 16
		case r == 92: // ['\','\']
			return 17
		case 97 <= r && r <= 100: // ['a','d']
			return 18
		case r == 101: // ['e','e']
			return 34
		case 102 <= r && r <= 119: // ['f','w']
			return 18
		case r == 120: // ['x','x']
			return 35
		case 121 <= r && r <= 122: // ['y','z']
			return 18
		}
		return NoState
	},
	// S10
	func(r rune) int {
		switch {
		case r == 33: // ['!','!']
			return 13
		case r == 35: // ['#','#']
			return 13
		case r == 36: // ['$','$']
			return 13
		case r == 45: // ['-','-']
			return 14
		case r == 46: // ['.','.']
			return 29
		case 48 <= r && r <= 57: // ['0','9']
			return 36
		case r == 63: // ['?','?']
			return 13
		case r == 64: // ['@','@']
			return 13
		case 65 <= r && r <= 68: // ['A','D']
			return 16
		case r == 69: // ['E','E']
			return 32
		case 70 <= r && r <= 90: // ['F','Z']
			return 16
		case r == 92: // ['\','\']
			return 17
		case 97 <= r && r <= 100: // ['a','d']
			return 18
		case r == 101: // ['e','e']
			return 34
		case 102 <= r && r <= 122: // ['f','z']
			return 18
		}
		return NoState
	},
	// S11
	func(r rune) int {
		switch {
		case r == 33: // ['!','!']
			return 13
		case r == 35: // ['#','#']
			return 13
		case r == 36: // ['$','$']
			return 13
		case r == 45: // ['-','-']
			return 14
		case r == 46: // ['.','.']
			return 13
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case r == 63: // ['?','?']
			return 13
		case r == 64: // ['@','@']
			return 13
		case 65 <= r && r <= 90: // ['A','Z']
			return 16
		case r == 92: // ['\','\']
			return 17
		case 97 <= r && r <= 122: // ['a','z']
			return 18
		}
		return NoState
	},
	// S12
	func(r rune) int {
		switch {
		case r == 33: // ['!','!']
			return 13
		case r == 35: // ['#','#']
			return 13
		case r == 36: // ['$','$']
			return 13
		case r == 45: // ['-','-']
			return 14
		case r == 46: // ['.','.']
			return 13
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case r == 63: // ['?','?']
			return 13
		case r == 64: // ['@','@']
			return 13
		case 65 <= r && r <= 90: // ['A','Z']
			return 16
		case r == 92: // ['\','\']
			return 17
		case 97 <= r && r <= 122: // ['a','z']
			return 18
		}
		return NoState
	},
	// S13
	func(r rune) int {
		switch {
		case r == 33: // ['!','!']
			return 13
		case r == 35: // ['#','#']
			return 13
		case r == 36: // ['$','$']
			return 13
		case r == 45: // ['-','-']
			return 14
		case r == 46: // ['.','.']
			return 13
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case r == 63: // ['?','?']
			return 13
		case r == 64: // ['@','@']
			return 13
		case 65 <= r && r <= 90: // ['A','Z']
			return 16
		case r == 92: // ['\','\']
			return 17
		case 97 <= r && r <= 122: // ['a','z']
			return 18
		}
		return NoState
	},
	// S14
	func(r rune) int {
		switch {
		case r == 33: // ['!','!']
			return 13
		case r == 35: // ['#','#']
			return 13
		case r == 36: // ['$','$']
			return 13
		case r == 45: // ['-','-']
			return 14
		case r == 46: // ['.','.']
			return 13
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case r == 63: // ['?','?']
			return 13
		case r == 64: // ['@','@']
			return 13
		case 65 <= r && r <= 90: // ['A','Z']
			return 16
		case r == 92: // ['\','\']
			return 17
		case 97 <= r && r <= 122: // ['a','z']
			return 18
		}
		return NoState
	},
	// S15
	func(r rune) int {
		switch {
		case r == 33: // ['!','!']
			return 13
		case r == 35: // ['#','#']
			return 13
		case r == 36: // ['$','$']
			return 13
		case r == 45: // ['-','-']
			return 14
		case r == 46: // ['.','.']
			return 13
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case r == 63: // ['?','?']
			return 13
		case r == 64: // ['@','@']
			return 13
		case 65 <= r && r <= 90: // ['A','Z']
			return 16
		case r == 92: // ['\','\']
			return 17
		case 97 <= r && r <= 122: // ['a','z']
			return 18
		}
		return NoState
	},
	// S16
	func(r rune) int {
		switch {
		case r == 33: // ['!','!']
			return 13
		case r == 35: // ['#','#']
			return 13
		case r == 36: // ['$','$']
			return 13
		case r == 45: // ['-','-']
			return 14
		case r == 46: // ['.','.']
			return 13
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case r == 63: // ['?','?']
			return 13
		case r == 64: // ['@','@']
			return 13
		case 65 <= r && r <= 90: // ['A','Z']
			return 16
		case r == 92: // ['\','\']
			return 17
		case 97 <= r && r <= 122: // ['a','z']
			return 18
		}
		return NoState
	},
	// S17
	func(r rune) int {
		switch {
		case r == 32: // [' ',' ']
			return 14
		}
		return NoState
	},
	// S18
	func(r rune) int {
		switch {
		case r == 33: // ['!','!']
			return 13
		case r == 35: // ['#','#']
			return 13
		case r == 36: // ['$','$']
			return 13
		case r == 45: // ['-','-']
			return 14
		case r == 46: // ['.','.']
			return 13
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case r == 63: // ['?','?']
			return 13
		case r == 64: // ['@','@']
			return 13
		case 65 <= r && r <= 90: // ['A','Z']
			return 16
		case r == 92: // ['\','\']
			return 17
		case 97 <= r && r <= 122: // ['a','z']
			return 18
		}
		return NoState
	},
	// S19
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S20
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 37
		case r == 39: // [''',''']
			return 37
		case 48 <= r && r <= 55: // ['0','7']
			return 38
		case r == 85: // ['U','U']
			return 39
		case r == 92: // ['\','\']
			return 37
		case r == 97: // ['a','a']
			return 37
		case r == 98: // ['b','b']
			return 37
		case r == 102: // ['f','f']
			return 37
		case r == 110: // ['n','n']
			return 37
		case r == 114: // ['r','r']
			return 37
		case r == 116: // ['t','t']
			return 37
		case r == 117: // ['u','u']
			return 40
		case r == 118: // ['v','v']
			return 37
		case r == 120: // ['x','x']
			return 41
		}
		return NoState
	},
	// S21
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 19
		case r == 92: // ['\','\']
			return 20
		default:
			return 21
		}
	},
	// S22
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S23
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 42
		case r == 69: // ['E','E']
			return 43
		case r == 101: // ['e','e']
			return 43
		}
		return NoState
	},
	// S24
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 44
		case 48 <= r && r <= 55: // ['0','7']
			return 45
		case 56 <= r && r <= 57: // ['8','9']
			return 46
		case r == 69: // ['E','E']
			return 47
		case r == 88: // ['X','X']
			return 48
		case r == 101: // ['e','e']
			return 47
		case r == 120: // ['x','x']
			return 48
		}
		return NoState
	},
	// S25
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 44
		case 48 <= r && r <= 57: // ['0','9']
			return 25
		case r == 69: // ['E','E']
			return 47
		case r == 101: // ['e','e']
			return 47
		}
		return NoState
	},
	// S26
	func(r rune) int {
		switch {
		case r == 33: // ['!','!']
			return 13
		case r == 35: // ['#','#']
			return 13
		case r == 36: // ['$','$']
			return 13
		case r == 45: // ['-','-']
			return 14
		case r == 46: // ['.','.']
			return 13
		case 48 <= r && r <= 57: // ['0','9']
			return 26
		case r == 63: // ['?','?']
			return 13
		case r == 64: // ['@','@']
			return 13
		case 65 <= r && r <= 90: // ['A','Z']
			return 16
		case r == 92: // ['\','\']
			return 17
		case 97 <= r && r <= 122: // ['a','z']
			return 18
		}
		return NoState
	},
	// S27
	func(r rune) int {
		switch {
		case r == 33: // ['!','!']
			return 13
		case r == 35: // ['#','#']
			return 13
		case r == 36: // ['$','$']
			return 13
		case r == 43: // ['+','+']
			return 49
		case r == 45: // ['-','-']
			return 50
		case r == 46: // ['.','.']
			return 13
		case 48 <= r && r <= 57: // ['0','9']
			return 51
		case r == 63: // ['?','?']
			return 13
		case r == 64: // ['@','@']
			return 13
		case 65 <= r && r <= 90: // ['A','Z']
			return 16
		case r == 92: // ['\','\']
			return 17
		case 97 <= r && r <= 122: // ['a','z']
			return 18
		}
		return NoState
	},
	// S28
	func(r rune) int {
		switch {
		case r == 33: // ['!','!']
			return 13
		case r == 35: // ['#','#']
			return 13
		case r == 36: // ['$','$']
			return 13
		case r == 43: // ['+','+']
			return 49
		case r == 45: // ['-','-']
			return 50
		case r == 46: // ['.','.']
			return 13
		case 48 <= r && r <= 57: // ['0','9']
			return 51
		case r == 63: // ['?','?']
			return 13
		case r == 64: // ['@','@']
			return 13
		case 65 <= r && r <= 90: // ['A','Z']
			return 16
		case r == 92: // ['\','\']
			return 17
		case 97 <= r && r <= 122: // ['a','z']
			return 18
		}
		return NoState
	},
	// S29
	func(r rune) int {
		switch {
		case r == 33: // ['!','!']
			return 13
		case r == 35: // ['#','#']
			return 13
		case r == 36: // ['$','$']
			return 13
		case r == 45: // ['-','-']
			return 14
		case r == 46: // ['.','.']
			return 13
		case 48 <= r && r <= 57: // ['0','9']
			return 52
		case r == 63: // ['?','?']
			return 13
		case r == 64: // ['@','@']
			return 13
		case 65 <= r && r <= 68: // ['A','D']
			return 16
		case r == 69: // ['E','E']
			return 53
		case 70 <= r && r <= 90: // ['F','Z']
			return 16
		case r == 92: // ['\','\']
			return 17
		case 97 <= r && r <= 100: // ['a','d']
			return 18
		case r == 101: // ['e','e']
			return 54
		case 102 <= r && r <= 122: // ['f','z']
			return 18
		}
		return NoState
	},
	// S30
	func(r rune) int {
		switch {
		case r == 33: // ['!','!']
			return 13
		case r == 35: // ['#','#']
			return 13
		case r == 36: // ['$','$']
			return 13
		case r == 45: // ['-','-']
			return 14
		case r == 46: // ['.','.']
			return 29
		case 48 <= r && r <= 55: // ['0','7']
			return 30
		case 56 <= r && r <= 57: // ['8','9']
			return 31
		case r == 63: // ['?','?']
			return 13
		case r == 64: // ['@','@']
			return 13
		case 65 <= r && r <= 68: // ['A','D']
			return 16
		case r == 69: // ['E','E']
			return 32
		case 70 <= r && r <= 90: // ['F','Z']
			return 16
		case r == 92: // ['\','\']
			return 17
		case 97 <= r && r <= 100: // ['a','d']
			return 18
		case r == 101: // ['e','e']
			return 34
		case 102 <= r && r <= 122: // ['f','z']
			return 18
		}
		return NoState
	},
	// S31
	func(r rune) int {
		switch {
		case r == 33: // ['!','!']
			return 13
		case r == 35: // ['#','#']
			return 13
		case r == 36: // ['$','$']
			return 13
		case r == 45: // ['-','-']
			return 14
		case r == 46: // ['.','.']
			return 29
		case 48 <= r && r <= 57: // ['0','9']
			return 31
		case r == 63: // ['?','?']
			return 13
		case r == 64: // ['@','@']
			return 13
		case 65 <= r && r <= 68: // ['A','D']
			return 16
		case r == 69: // ['E','E']
			return 32
		case 70 <= r && r <= 90: // ['F','Z']
			return 16
		case r == 92: // ['\','\']
			return 17
		case 97 <= r && r <= 100: // ['a','d']
			return 18
		case r == 101: // ['e','e']
			return 34
		case 102 <= r && r <= 122: // ['f','z']
			return 18
		}
		return NoState
	},
	// S32
	func(r rune) int {
		switch {
		case r == 33: // ['!','!']
			return 13
		case r == 35: // ['#','#']
			return 13
		case r == 36: // ['$','$']
			return 13
		case r == 43: // ['+','+']
			return 55
		case r == 45: // ['-','-']
			return 56
		case r == 46: // ['.','.']
			return 13
		case 48 <= r && r <= 57: // ['0','9']
			return 57
		case r == 63: // ['?','?']
			return 13
		case r == 64: // ['@','@']
			return 13
		case 65 <= r && r <= 90: // ['A','Z']
			return 16
		case r == 92: // ['\','\']
			return 17
		case 97 <= r && r <= 122: // ['a','z']
			return 18
		}
		return NoState
	},
	// S33
	func(r rune) int {
		switch {
		case r == 33: // ['!','!']
			return 13
		case r == 35: // ['#','#']
			return 13
		case r == 36: // ['$','$']
			return 13
		case r == 45: // ['-','-']
			return 14
		case r == 46: // ['.','.']
			return 13
		case 48 <= r && r <= 57: // ['0','9']
			return 58
		case r == 63: // ['?','?']
			return 13
		case r == 64: // ['@','@']
			return 13
		case 65 <= r && r <= 70: // ['A','F']
			return 59
		case 71 <= r && r <= 90: // ['G','Z']
			return 16
		case r == 92: // ['\','\']
			return 17
		case 97 <= r && r <= 102: // ['a','f']
			return 60
		case 103 <= r && r <= 122: // ['g','z']
			return 18
		}
		return NoState
	},
	// S34
	func(r rune) int {
		switch {
		case r == 33: // ['!','!']
			return 13
		case r == 35: // ['#','#']
			return 13
		case r == 36: // ['$','$']
			return 13
		case r == 43: // ['+','+']
			return 55
		case r == 45: // ['-','-']
			return 56
		case r == 46: // ['.','.']
			return 13
		case 48 <= r && r <= 57: // ['0','9']
			return 57
		case r == 63: // ['?','?']
			return 13
		case r == 64: // ['@','@']
			return 13
		case 65 <= r && r <= 90: // ['A','Z']
			return 16
		case r == 92: // ['\','\']
			return 17
		case 97 <= r && r <= 122: // ['a','z']
			return 18
		}
		return NoState
	},
	// S35
	func(r rune) int {
		switch {
		case r == 33: // ['!','!']
			return 13
		case r == 35: // ['#','#']
			return 13
		case r == 36: // ['$','$']
			return 13
		case r == 45: // ['-','-']
			return 14
		case r == 46: // ['.','.']
			return 13
		case 48 <= r && r <= 57: // ['0','9']
			return 58
		case r == 63: // ['?','?']
			return 13
		case r == 64: // ['@','@']
			return 13
		case 65 <= r && r <= 70: // ['A','F']
			return 59
		case 71 <= r && r <= 90: // ['G','Z']
			return 16
		case r == 92: // ['\','\']
			return 17
		case 97 <= r && r <= 102: // ['a','f']
			return 60
		case 103 <= r && r <= 122: // ['g','z']
			return 18
		}
		return NoState
	},
	// S36
	func(r rune) int {
		switch {
		case r == 33: // ['!','!']
			return 13
		case r == 35: // ['#','#']
			return 13
		case r == 36: // ['$','$']
			return 13
		case r == 45: // ['-','-']
			return 14
		case r == 46: // ['.','.']
			return 29
		case 48 <= r && r <= 57: // ['0','9']
			return 36
		case r == 63: // ['?','?']
			return 13
		case r == 64: // ['@','@']
			return 13
		case 65 <= r && r <= 68: // ['A','D']
			return 16
		case r == 69: // ['E','E']
			return 32
		case 70 <= r && r <= 90: // ['F','Z']
			return 16
		case r == 92: // ['\','\']
			return 17
		case 97 <= r && r <= 100: // ['a','d']
			return 18
		case r == 101: // ['e','e']
			return 34
		case 102 <= r && r <= 122: // ['f','z']
			return 18
		}
		return NoState
	},
	// S37
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 19
		case r == 92: // ['\','\']
			return 20
		default:
			return 21
		}
	},
	// S38
	func(r rune) int {
		switch {
		case 48 <= r && r <= 55: // ['0','7']
			return 61
		}
		return NoState
	},
	// S39
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 62
		case 65 <= r && r <= 70: // ['A','F']
			return 62
		case 97 <= r && r <= 102: // ['a','f']
			return 62
		}
		return NoState
	},
	// S40
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 63
		case 65 <= r && r <= 70: // ['A','F']
			return 63
		case 97 <= r && r <= 102: // ['a','f']
			return 63
		}
		return NoState
	},
	// S41
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 64
		case 65 <= r && r <= 70: // ['A','F']
			return 64
		case 97 <= r && r <= 102: // ['a','f']
			return 64
		}
		return NoState
	},
	// S42
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 42
		}
		return NoState
	},
	// S43
	func(r rune) int {
		switch {
		case r == 43: // ['+','+']
			return 49
		case r == 45: // ['-','-']
			return 49
		case 48 <= r && r <= 57: // ['0','9']
			return 65
		}
		return NoState
	},
	// S44
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 66
		case r == 69: // ['E','E']
			return 67
		case r == 101: // ['e','e']
			return 67
		}
		return NoState
	},
	// S45
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 44
		case 48 <= r && r <= 55: // ['0','7']
			return 45
		case 56 <= r && r <= 57: // ['8','9']
			return 46
		case r == 69: // ['E','E']
			return 47
		case r == 101: // ['e','e']
			return 47
		}
		return NoState
	},
	// S46
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 44
		case 48 <= r && r <= 57: // ['0','9']
			return 46
		case r == 69: // ['E','E']
			return 47
		case r == 101: // ['e','e']
			return 47
		}
		return NoState
	},
	// S47
	func(r rune) int {
		switch {
		case r == 43: // ['+','+']
			return 55
		case r == 45: // ['-','-']
			return 55
		case 48 <= r && r <= 57: // ['0','9']
			return 68
		}
		return NoState
	},
	// S48
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 69
		case 65 <= r && r <= 70: // ['A','F']
			return 69
		case 97 <= r && r <= 102: // ['a','f']
			return 69
		}
		return NoState
	},
	// S49
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 65
		}
		return NoState
	},
	// S50
	func(r rune) int {
		switch {
		case r == 33: // ['!','!']
			return 13
		case r == 35: // ['#','#']
			return 13
		case r == 36: // ['$','$']
			return 13
		case r == 45: // ['-','-']
			return 14
		case r == 46: // ['.','.']
			return 13
		case 48 <= r && r <= 57: // ['0','9']
			return 51
		case r == 63: // ['?','?']
			return 13
		case r == 64: // ['@','@']
			return 13
		case 65 <= r && r <= 90: // ['A','Z']
			return 16
		case r == 92: // ['\','\']
			return 17
		case 97 <= r && r <= 122: // ['a','z']
			return 18
		}
		return NoState
	},
	// S51
	func(r rune) int {
		switch {
		case r == 33: // ['!','!']
			return 13
		case r == 35: // ['#','#']
			return 13
		case r == 36: // ['$','$']
			return 13
		case r == 45: // ['-','-']
			return 14
		case r == 46: // ['.','.']
			return 13
		case 48 <= r && r <= 57: // ['0','9']
			return 51
		case r == 63: // ['?','?']
			return 13
		case r == 64: // ['@','@']
			return 13
		case 65 <= r && r <= 90: // ['A','Z']
			return 16
		case r == 92: // ['\','\']
			return 17
		case 97 <= r && r <= 122: // ['a','z']
			return 18
		}
		return NoState
	},
	// S52
	func(r rune) int {
		switch {
		case r == 33: // ['!','!']
			return 13
		case r == 35: // ['#','#']
			return 13
		case r == 36: // ['$','$']
			return 13
		case r == 45: // ['-','-']
			return 14
		case r == 46: // ['.','.']
			return 13
		case 48 <= r && r <= 57: // ['0','9']
			return 52
		case r == 63: // ['?','?']
			return 13
		case r == 64: // ['@','@']
			return 13
		case 65 <= r && r <= 68: // ['A','D']
			return 16
		case r == 69: // ['E','E']
			return 70
		case 70 <= r && r <= 90: // ['F','Z']
			return 16
		case r == 92: // ['\','\']
			return 17
		case 97 <= r && r <= 100: // ['a','d']
			return 18
		case r == 101: // ['e','e']
			return 71
		case 102 <= r && r <= 122: // ['f','z']
			return 18
		}
		return NoState
	},
	// S53
	func(r rune) int {
		switch {
		case r == 33: // ['!','!']
			return 13
		case r == 35: // ['#','#']
			return 13
		case r == 36: // ['$','$']
			return 13
		case r == 43: // ['+','+']
			return 72
		case r == 45: // ['-','-']
			return 73
		case r == 46: // ['.','.']
			return 13
		case 48 <= r && r <= 57: // ['0','9']
			return 74
		case r == 63: // ['?','?']
			return 13
		case r == 64: // ['@','@']
			return 13
		case 65 <= r && r <= 90: // ['A','Z']
			return 16
		case r == 92: // ['\','\']
			return 17
		case 97 <= r && r <= 122: // ['a','z']
			return 18
		}
		return NoState
	},
	// S54
	func(r rune) int {
		switch {
		case r == 33: // ['!','!']
			return 13
		case r == 35: // ['#','#']
			return 13
		case r == 36: // ['$','$']
			return 13
		case r == 43: // ['+','+']
			return 72
		case r == 45: // ['-','-']
			return 73
		case r == 46: // ['.','.']
			return 13
		case 48 <= r && r <= 57: // ['0','9']
			return 74
		case r == 63: // ['?','?']
			return 13
		case r == 64: // ['@','@']
			return 13
		case 65 <= r && r <= 90: // ['A','Z']
			return 16
		case r == 92: // ['\','\']
			return 17
		case 97 <= r && r <= 122: // ['a','z']
			return 18
		}
		return NoState
	},
	// S55
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 68
		}
		return NoState
	},
	// S56
	func(r rune) int {
		switch {
		case r == 33: // ['!','!']
			return 13
		case r == 35: // ['#','#']
			return 13
		case r == 36: // ['$','$']
			return 13
		case r == 45: // ['-','-']
			return 14
		case r == 46: // ['.','.']
			return 13
		case 48 <= r && r <= 57: // ['0','9']
			return 57
		case r == 63: // ['?','?']
			return 13
		case r == 64: // ['@','@']
			return 13
		case 65 <= r && r <= 90: // ['A','Z']
			return 16
		case r == 92: // ['\','\']
			return 17
		case 97 <= r && r <= 122: // ['a','z']
			return 18
		}
		return NoState
	},
	// S57
	func(r rune) int {
		switch {
		case r == 33: // ['!','!']
			return 13
		case r == 35: // ['#','#']
			return 13
		case r == 36: // ['$','$']
			return 13
		case r == 45: // ['-','-']
			return 14
		case r == 46: // ['.','.']
			return 13
		case 48 <= r && r <= 57: // ['0','9']
			return 57
		case r == 63: // ['?','?']
			return 13
		case r == 64: // ['@','@']
			return 13
		case 65 <= r && r <= 90: // ['A','Z']
			return 16
		case r == 92: // ['\','\']
			return 17
		case 97 <= r && r <= 122: // ['a','z']
			return 18
		}
		return NoState
	},
	// S58
	func(r rune) int {
		switch {
		case r == 33: // ['!','!']
			return 13
		case r == 35: // ['#','#']
			return 13
		case r == 36: // ['$','$']
			return 13
		case r == 45: // ['-','-']
			return 14
		case r == 46: // ['.','.']
			return 13
		case 48 <= r && r <= 57: // ['0','9']
			return 58
		case r == 63: // ['?','?']
			return 13
		case r == 64: // ['@','@']
			return 13
		case 65 <= r && r <= 70: // ['A','F']
			return 59
		case 71 <= r && r <= 90: // ['G','Z']
			return 16
		case r == 92: // ['\','\']
			return 17
		case 97 <= r && r <= 102: // ['a','f']
			return 60
		case 103 <= r && r <= 122: // ['g','z']
			return 18
		}
		return NoState
	},
	// S59
	func(r rune) int {
		switch {
		case r == 33: // ['!','!']
			return 13
		case r == 35: // ['#','#']
			return 13
		case r == 36: // ['$','$']
			return 13
		case r == 45: // ['-','-']
			return 14
		case r == 46: // ['.','.']
			return 13
		case 48 <= r && r <= 57: // ['0','9']
			return 58
		case r == 63: // ['?','?']
			return 13
		case r == 64: // ['@','@']
			return 13
		case 65 <= r && r <= 70: // ['A','F']
			return 59
		case 71 <= r && r <= 90: // ['G','Z']
			return 16
		case r == 92: // ['\','\']
			return 17
		case 97 <= r && r <= 102: // ['a','f']
			return 60
		case 103 <= r && r <= 122: // ['g','z']
			return 18
		}
		return NoState
	},
	// S60
	func(r rune) int {
		switch {
		case r == 33: // ['!','!']
			return 13
		case r == 35: // ['#','#']
			return 13
		case r == 36: // ['$','$']
			return 13
		case r == 45: // ['-','-']
			return 14
		case r == 46: // ['.','.']
			return 13
		case 48 <= r && r <= 57: // ['0','9']
			return 58
		case r == 63: // ['?','?']
			return 13
		case r == 64: // ['@','@']
			return 13
		case 65 <= r && r <= 70: // ['A','F']
			return 59
		case 71 <= r && r <= 90: // ['G','Z']
			return 16
		case r == 92: // ['\','\']
			return 17
		case 97 <= r && r <= 102: // ['a','f']
			return 60
		case 103 <= r && r <= 122: // ['g','z']
			return 18
		}
		return NoState
	},
	// S61
	func(r rune) int {
		switch {
		case 48 <= r && r <= 55: // ['0','7']
			return 75
		}
		return NoState
	},
	// S62
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 76
		case 65 <= r && r <= 70: // ['A','F']
			return 76
		case 97 <= r && r <= 102: // ['a','f']
			return 76
		}
		return NoState
	},
	// S63
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 77
		case 65 <= r && r <= 70: // ['A','F']
			return 77
		case 97 <= r && r <= 102: // ['a','f']
			return 77
		}
		return NoState
	},
	// S64
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 78
		case 65 <= r && r <= 70: // ['A','F']
			return 78
		case 97 <= r && r <= 102: // ['a','f']
			return 78
		}
		return NoState
	},
	// S65
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 65
		}
		return NoState
	},
	// S66
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 66
		case r == 69: // ['E','E']
			return 79
		case r == 101: // ['e','e']
			return 79
		}
		return NoState
	},
	// S67
	func(r rune) int {
		switch {
		case r == 43: // ['+','+']
			return 72
		case r == 45: // ['-','-']
			return 72
		case 48 <= r && r <= 57: // ['0','9']
			return 80
		}
		return NoState
	},
	// S68
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 68
		}
		return NoState
	},
	// S69
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 69
		case 65 <= r && r <= 70: // ['A','F']
			return 69
		case 97 <= r && r <= 102: // ['a','f']
			return 69
		}
		return NoState
	},
	// S70
	func(r rune) int {
		switch {
		case r == 33: // ['!','!']
			return 13
		case r == 35: // ['#','#']
			return 13
		case r == 36: // ['$','$']
			return 13
		case r == 43: // ['+','+']
			return 81
		case r == 45: // ['-','-']
			return 82
		case r == 46: // ['.','.']
			return 13
		case 48 <= r && r <= 57: // ['0','9']
			return 83
		case r == 63: // ['?','?']
			return 13
		case r == 64: // ['@','@']
			return 13
		case 65 <= r && r <= 90: // ['A','Z']
			return 16
		case r == 92: // ['\','\']
			return 17
		case 97 <= r && r <= 122: // ['a','z']
			return 18
		}
		return NoState
	},
	// S71
	func(r rune) int {
		switch {
		case r == 33: // ['!','!']
			return 13
		case r == 35: // ['#','#']
			return 13
		case r == 36: // ['$','$']
			return 13
		case r == 43: // ['+','+']
			return 81
		case r == 45: // ['-','-']
			return 82
		case r == 46: // ['.','.']
			return 13
		case 48 <= r && r <= 57: // ['0','9']
			return 83
		case r == 63: // ['?','?']
			return 13
		case r == 64: // ['@','@']
			return 13
		case 65 <= r && r <= 90: // ['A','Z']
			return 16
		case r == 92: // ['\','\']
			return 17
		case 97 <= r && r <= 122: // ['a','z']
			return 18
		}
		return NoState
	},
	// S72
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 80
		}
		return NoState
	},
	// S73
	func(r rune) int {
		switch {
		case r == 33: // ['!','!']
			return 13
		case r == 35: // ['#','#']
			return 13
		case r == 36: // ['$','$']
			return 13
		case r == 45: // ['-','-']
			return 14
		case r == 46: // ['.','.']
			return 13
		case 48 <= r && r <= 57: // ['0','9']
			return 74
		case r == 63: // ['?','?']
			return 13
		case r == 64: // ['@','@']
			return 13
		case 65 <= r && r <= 90: // ['A','Z']
			return 16
		case r == 92: // ['\','\']
			return 17
		case 97 <= r && r <= 122: // ['a','z']
			return 18
		}
		return NoState
	},
	// S74
	func(r rune) int {
		switch {
		case r == 33: // ['!','!']
			return 13
		case r == 35: // ['#','#']
			return 13
		case r == 36: // ['$','$']
			return 13
		case r == 45: // ['-','-']
			return 14
		case r == 46: // ['.','.']
			return 13
		case 48 <= r && r <= 57: // ['0','9']
			return 74
		case r == 63: // ['?','?']
			return 13
		case r == 64: // ['@','@']
			return 13
		case 65 <= r && r <= 90: // ['A','Z']
			return 16
		case r == 92: // ['\','\']
			return 17
		case 97 <= r && r <= 122: // ['a','z']
			return 18
		}
		return NoState
	},
	// S75
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 19
		case r == 92: // ['\','\']
			return 20
		default:
			return 21
		}
	},
	// S76
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 84
		case 65 <= r && r <= 70: // ['A','F']
			return 84
		case 97 <= r && r <= 102: // ['a','f']
			return 84
		}
		return NoState
	},
	// S77
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 85
		case 65 <= r && r <= 70: // ['A','F']
			return 85
		case 97 <= r && r <= 102: // ['a','f']
			return 85
		}
		return NoState
	},
	// S78
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 19
		case r == 92: // ['\','\']
			return 20
		default:
			return 21
		}
	},
	// S79
	func(r rune) int {
		switch {
		case r == 43: // ['+','+']
			return 81
		case r == 45: // ['-','-']
			return 81
		case 48 <= r && r <= 57: // ['0','9']
			return 86
		}
		return NoState
	},
	// S80
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 80
		}
		return NoState
	},
	// S81
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 86
		}
		return NoState
	},
	// S82
	func(r rune) int {
		switch {
		case r == 33: // ['!','!']
			return 13
		case r == 35: // ['#','#']
			return 13
		case r == 36: // ['$','$']
			return 13
		case r == 45: // ['-','-']
			return 14
		case r == 46: // ['.','.']
			return 13
		case 48 <= r && r <= 57: // ['0','9']
			return 83
		case r == 63: // ['?','?']
			return 13
		case r == 64: // ['@','@']
			return 13
		case 65 <= r && r <= 90: // ['A','Z']
			return 16
		case r == 92: // ['\','\']
			return 17
		case 97 <= r && r <= 122: // ['a','z']
			return 18
		}
		return NoState
	},
	// S83
	func(r rune) int {
		switch {
		case r == 33: // ['!','!']
			return 13
		case r == 35: // ['#','#']
			return 13
		case r == 36: // ['$','$']
			return 13
		case r == 45: // ['-','-']
			return 14
		case r == 46: // ['.','.']
			return 13
		case 48 <= r && r <= 57: // ['0','9']
			return 83
		case r == 63: // ['?','?']
			return 13
		case r == 64: // ['@','@']
			return 13
		case 65 <= r && r <= 90: // ['A','Z']
			return 16
		case r == 92: // ['\','\']
			return 17
		case 97 <= r && r <= 122: // ['a','z']
			return 18
		}
		return NoState
	},
	// S84
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 87
		case 65 <= r && r <= 70: // ['A','F']
			return 87
		case 97 <= r && r <= 102: // ['a','f']
			return 87
		}
		return NoState
	},
	// S85
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 88
		case 65 <= r && r <= 70: // ['A','F']
			return 88
		case 97 <= r && r <= 102: // ['a','f']
			return 88
		}
		return NoState
	},
	// S86
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 86
		}
		return NoState
	},
	// S87
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 89
		case 65 <= r && r <= 70: // ['A','F']
			return 89
		case 97 <= r && r <= 102: // ['a','f']
			return 89
		}
		return NoState
	},
	// S88
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 19
		case r == 92: // ['\','\']
			return 20
		default:
			return 21
		}
	},
	// S89
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 90
		case 65 <= r && r <= 70: // ['A','F']
			return 90
		case 97 <= r && r <= 102: // ['a','f']
			return 90
		}
		return NoState
	},
	// S90
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 91
		case 65 <= r && r <= 70: // ['A','F']
			return 91
		case 97 <= r && r <= 102: // ['a','f']
			return 91
		}
		return NoState
	},
	// S91
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 92
		case 65 <= r && r <= 70: // ['A','F']
			return 92
		case 97 <= r && r <= 102: // ['a','f']
			return 92
		}
		return NoState
	},
	// S92
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 19
		case r == 92: // ['\','\']
			return 20
		default:
			return 21
		}
	},
}
