// Code generated by goderive DO NOT EDIT.

package mini

import (
	ast "github.com/awalterschulze/gominikanren/sexpr/ast"
)

// deriveFmapR returns a list where each element of the input list has been morphed by the input function.
func deriveFmapR(f func(*ast.List) *ast.SExpr, list []*ast.List) []*ast.SExpr {
	out := make([]*ast.SExpr, len(list))
	for i, elem := range list {
		out[i] = f(elem)
	}
	return out
}
