(begin
  (display (cons 'a 'b))
  (newline)
  (display (cons '(a) 'b))
  (newline)
  (display (cons '(a) '(b)))
  (newline)
  (display (cons 'a '(b)))
  (newline)
  (display (cons '(a) '(b c)))
  (newline)
  (display (cons 'a '(b c)))
  (newline)
  (display (cons '(a b) '(c d)))
  (newline)
  (display (cons 'a '()))
  (newline)
  (display (cons '(a) '()))
  (newline)
  (display (cons '(a b) '()))
  (newline)
  (display (cons '() '()))
  (newline)
  (display (cons '() '(b)))
  (newline)
  (display (cons '() '(b c)))
  (newline)
  (display (append '() '(B C)))
  (newline)
  (display (append '(A) 'B))
  (newline)
  (display (pair? '(A)))
  (newline)
)