// Code generated by gocc; DO NOT EDIT.

package parser

const numNTSymbols = 6

type (
	gotoTable [numStates]gotoRow
	gotoRow   [numNTSymbols]int
)

var gotoTab = gotoTable{
	gotoRow{ // S0
		-1, // S'
		1,  // SExpr
		3,  // List
		-1, // ContinueList
		4,  // QuotedList
		2,  // Atom
	},
	gotoRow{ // S1
		-1, // S'
		-1, // SExpr
		-1, // List
		-1, // ContinueList
		-1, // QuotedList
		-1, // Atom
	},
	gotoRow{ // S2
		-1, // S'
		-1, // SExpr
		-1, // List
		-1, // ContinueList
		-1, // QuotedList
		-1, // Atom
	},
	gotoRow{ // S3
		-1, // S'
		-1, // SExpr
		-1, // List
		-1, // ContinueList
		-1, // QuotedList
		-1, // Atom
	},
	gotoRow{ // S4
		-1, // S'
		-1, // SExpr
		-1, // List
		-1, // ContinueList
		-1, // QuotedList
		-1, // Atom
	},
	gotoRow{ // S5
		-1, // S'
		12, // SExpr
		14, // List
		-1, // ContinueList
		15, // QuotedList
		13, // Atom
	},
	gotoRow{ // S6
		-1, // S'
		-1, // SExpr
		-1, // List
		-1, // ContinueList
		-1, // QuotedList
		-1, // Atom
	},
	gotoRow{ // S7
		-1, // S'
		-1, // SExpr
		-1, // List
		-1, // ContinueList
		-1, // QuotedList
		-1, // Atom
	},
	gotoRow{ // S8
		-1, // S'
		-1, // SExpr
		-1, // List
		-1, // ContinueList
		-1, // QuotedList
		-1, // Atom
	},
	gotoRow{ // S9
		-1, // S'
		-1, // SExpr
		-1, // List
		-1, // ContinueList
		-1, // QuotedList
		-1, // Atom
	},
	gotoRow{ // S10
		-1, // S'
		-1, // SExpr
		-1, // List
		-1, // ContinueList
		-1, // QuotedList
		-1, // Atom
	},
	gotoRow{ // S11
		-1, // S'
		-1, // SExpr
		-1, // List
		-1, // ContinueList
		-1, // QuotedList
		-1, // Atom
	},
	gotoRow{ // S12
		-1, // S'
		-1, // SExpr
		-1, // List
		-1, // ContinueList
		-1, // QuotedList
		-1, // Atom
	},
	gotoRow{ // S13
		-1, // S'
		-1, // SExpr
		-1, // List
		-1, // ContinueList
		-1, // QuotedList
		-1, // Atom
	},
	gotoRow{ // S14
		-1, // S'
		-1, // SExpr
		-1, // List
		-1, // ContinueList
		-1, // QuotedList
		-1, // Atom
	},
	gotoRow{ // S15
		-1, // S'
		-1, // SExpr
		-1, // List
		-1, // ContinueList
		-1, // QuotedList
		-1, // Atom
	},
	gotoRow{ // S16
		-1, // S'
		27, // SExpr
		14, // List
		-1, // ContinueList
		15, // QuotedList
		13, // Atom
	},
	gotoRow{ // S17
		-1, // S'
		-1, // SExpr
		-1, // List
		-1, // ContinueList
		-1, // QuotedList
		-1, // Atom
	},
	gotoRow{ // S18
		-1, // S'
		-1, // SExpr
		-1, // List
		-1, // ContinueList
		-1, // QuotedList
		-1, // Atom
	},
	gotoRow{ // S19
		-1, // S'
		-1, // SExpr
		-1, // List
		-1, // ContinueList
		-1, // QuotedList
		-1, // Atom
	},
	gotoRow{ // S20
		-1, // S'
		-1, // SExpr
		-1, // List
		-1, // ContinueList
		-1, // QuotedList
		-1, // Atom
	},
	gotoRow{ // S21
		-1, // S'
		-1, // SExpr
		-1, // List
		-1, // ContinueList
		-1, // QuotedList
		-1, // Atom
	},
	gotoRow{ // S22
		-1, // S'
		-1, // SExpr
		-1, // List
		-1, // ContinueList
		-1, // QuotedList
		-1, // Atom
	},
	gotoRow{ // S23
		-1, // S'
		-1, // SExpr
		-1, // List
		-1, // ContinueList
		-1, // QuotedList
		-1, // Atom
	},
	gotoRow{ // S24
		-1, // S'
		30, // SExpr
		14, // List
		-1, // ContinueList
		15, // QuotedList
		13, // Atom
	},
	gotoRow{ // S25
		-1, // S'
		-1, // SExpr
		-1, // List
		-1, // ContinueList
		-1, // QuotedList
		-1, // Atom
	},
	gotoRow{ // S26
		-1, // S'
		32, // SExpr
		14, // List
		33, // ContinueList
		15, // QuotedList
		13, // Atom
	},
	gotoRow{ // S27
		-1, // S'
		-1, // SExpr
		-1, // List
		-1, // ContinueList
		-1, // QuotedList
		-1, // Atom
	},
	gotoRow{ // S28
		-1, // S'
		-1, // SExpr
		-1, // List
		-1, // ContinueList
		-1, // QuotedList
		-1, // Atom
	},
	gotoRow{ // S29
		-1, // S'
		36, // SExpr
		14, // List
		-1, // ContinueList
		15, // QuotedList
		13, // Atom
	},
	gotoRow{ // S30
		-1, // S'
		-1, // SExpr
		-1, // List
		-1, // ContinueList
		-1, // QuotedList
		-1, // Atom
	},
	gotoRow{ // S31
		-1, // S'
		-1, // SExpr
		-1, // List
		-1, // ContinueList
		-1, // QuotedList
		-1, // Atom
	},
	gotoRow{ // S32
		-1, // S'
		-1, // SExpr
		-1, // List
		-1, // ContinueList
		-1, // QuotedList
		-1, // Atom
	},
	gotoRow{ // S33
		-1, // S'
		-1, // SExpr
		-1, // List
		-1, // ContinueList
		-1, // QuotedList
		-1, // Atom
	},
	gotoRow{ // S34
		-1, // S'
		-1, // SExpr
		-1, // List
		-1, // ContinueList
		-1, // QuotedList
		-1, // Atom
	},
	gotoRow{ // S35
		-1, // S'
		32, // SExpr
		14, // List
		42, // ContinueList
		15, // QuotedList
		13, // Atom
	},
	gotoRow{ // S36
		-1, // S'
		-1, // SExpr
		-1, // List
		-1, // ContinueList
		-1, // QuotedList
		-1, // Atom
	},
	gotoRow{ // S37
		-1, // S'
		-1, // SExpr
		-1, // List
		-1, // ContinueList
		-1, // QuotedList
		-1, // Atom
	},
	gotoRow{ // S38
		-1, // S'
		-1, // SExpr
		-1, // List
		-1, // ContinueList
		-1, // QuotedList
		-1, // Atom
	},
	gotoRow{ // S39
		-1, // S'
		32, // SExpr
		14, // List
		45, // ContinueList
		15, // QuotedList
		13, // Atom
	},
	gotoRow{ // S40
		-1, // S'
		-1, // SExpr
		-1, // List
		-1, // ContinueList
		-1, // QuotedList
		-1, // Atom
	},
	gotoRow{ // S41
		-1, // S'
		46, // SExpr
		14, // List
		-1, // ContinueList
		15, // QuotedList
		13, // Atom
	},
	gotoRow{ // S42
		-1, // S'
		-1, // SExpr
		-1, // List
		-1, // ContinueList
		-1, // QuotedList
		-1, // Atom
	},
	gotoRow{ // S43
		-1, // S'
		-1, // SExpr
		-1, // List
		-1, // ContinueList
		-1, // QuotedList
		-1, // Atom
	},
	gotoRow{ // S44
		-1, // S'
		32, // SExpr
		14, // List
		48, // ContinueList
		15, // QuotedList
		13, // Atom
	},
	gotoRow{ // S45
		-1, // S'
		-1, // SExpr
		-1, // List
		-1, // ContinueList
		-1, // QuotedList
		-1, // Atom
	},
	gotoRow{ // S46
		-1, // S'
		-1, // SExpr
		-1, // List
		-1, // ContinueList
		-1, // QuotedList
		-1, // Atom
	},
	gotoRow{ // S47
		-1, // S'
		-1, // SExpr
		-1, // List
		-1, // ContinueList
		-1, // QuotedList
		-1, // Atom
	},
	gotoRow{ // S48
		-1, // S'
		-1, // SExpr
		-1, // List
		-1, // ContinueList
		-1, // QuotedList
		-1, // Atom
	},
	gotoRow{ // S49
		-1, // S'
		-1, // SExpr
		-1, // List
		-1, // ContinueList
		-1, // QuotedList
		-1, // Atom
	},
	gotoRow{ // S50
		-1, // S'
		-1, // SExpr
		-1, // List
		-1, // ContinueList
		-1, // QuotedList
		-1, // Atom
	},
}
