name: Go

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.x

    - name: Fetch dependencies
      run: go mod download -x

    - name: Install tools
      run: go install -x github.com/goccmack/gocc

    - name: gocc
      working-directory: ./sexpr
      run: gocc sexpr.bnf

    - name: Test
      run: go test -v -count=1 -short ./...

    - name: Vet
      run: go vet ./...

    - name: diff
      run: git diff --exit-code .

